//
//  Group.h
//  FrankApp
//
//  Generated by Ian Terrell on 04/16/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "FrankObject.h"


@interface Group : FrankObject {
  NSString *name;

  NSArray *_users;
}

@property(nonatomic,retain) NSString *name;


@property(nonatomic,retain) NSArray *_users;
-(NSArray *)users;
-(NSArray *)usersWithReload;
-(int)usersCount;


@end
