//
//  Opinion.h
//  FrankApp
//
//  Generated by Ian Terrell on 04/16/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "FrankObject.h"

@class User;

@interface Opinion : FrankObject {
  NSString *value;
  NSNumber *userPk;

  User *_user;
}

@property(nonatomic,retain) NSString *value;
@property(nonatomic,retain) NSNumber *userPk;

@property(nonatomic,retain) User *_user;
-(User *)user;
-(User *)userWithReload;
-(void)setUser:(User *)obj;



@end
